### ISSUE TITLE
运行报错：缺sendNotify

### ISSUE THREAD

**Issue by richadlee** [2079898548/jd_lzsnmb#20]
![image](https://user-images.githubusercontent.com/31947064/147893875-6274a746-99fc-4759-862f-01d85e421514.png)

看到仓库目录好像也没有sendNotify文件

**Comment by xxp2277** [comment]
从别的库复制一个到脚本目录即可，或者把本py文件复制到有sendNotify.py的文件夹中去运行。

**Comment by By-The** [comment]
> 从别的库复制一个到脚本目录即可，或者把本py文件复制到有sendNotify.py的文件夹中去运行。

![image](https://user-images.githubusercontent.com/67124953/148644762-82d7844e-f9b0-40e8-8b79-a136be547bf1.png)
