### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by is101101** [2079898548/jd_lzsnmb#3]
# 开始执行... 2021-11-06 21:13:57

Traceback (most recent call last):
  File "jd_Evaluation.py", line 19, in <module>
    from sendNotify.py import send
  File "/ql/scripts/sendNotify.py", line 1
    /*
    ^
SyntaxError: invalid syntax

## 执行结束... 2021-11-06 21:13:57 耗时 0 秒

**Comment by Ocyss** [comment]
这是你推送文件的问题。
可以换这个试试
https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_older.py

**Comment by Ocyss** [comment]
> 这是你推送文件的问题。 可以换这个试试 https://github.com/Oreomeow/checkinpanel/blob/master/notify_mtr_older.py

.....这个试试吧。
https://github.com/Mashiro2000/HeyTapTask/blob/main/sendNotify.py

**Comment by is101101** [comment]
多谢。

**Comment by is101101** [comment]
已解决！
#from sendNotify import send
from notify import send
