### ISSUE TITLE
拉取失败

### ISSUE THREAD

**Issue by ghost** [2079898548/jd_lzsnmb#7]
下载 main_jd_Evaluation.py 成功...  main_jd_Evaluation.py -> 添加失败(Invalid cron expression)
请问这个怎么办，直接加文件倒是可以运行，但是这样更新不太方便

**Comment by Ocyss** [comment]
修复好了，这是新拉库地址。
ql raw https://raw.githubusercontent.com/qiu-lzsnmb/jd_lzsnmb/jd/Evaluation.py

**Comment by ghost** [comment]
thank u
